stages:
  - test

variables:
  GO111MODULES: 'on'

test:
  image: golang:1
  tags: [unprivileged, shell/sh, live]
  stage: test
  coverage: '/^total:\s*\(statements\)\s*(\d+\.\d+%)$/'
  artifacts:
    name: coverage
    expire_in: 1 hour
    paths:
      - cover.out
      - cover.html
  script:
    - go test -race -count 100 -coverprofile=cover.out
    - go tool cover -html cover.out -o cover.html
    - go tool cover -func cover.out
