version: '2.1'

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/build
    environment:
      GO111MODULE: 'on'
    steps:
    - checkout
    - run: go test -coverprofile=cover.out -covermode=atomic .
    - run: go tool cover -func=cover.out
